### ISSUE TITLE
Artefacts in Clover Noise

### ISSUE THREAD

**Issue by Articdive** [ValgoBoi/clover-noise#1]
Just wanted to let you know that in the Java Implementation we have some pretty bad artefacts along the xy-diagonal reoccurring. Here are some images (they are using the original code):
![image](https://user-images.githubusercontent.com/13535885/108517025-2f25d900-72c7-11eb-9aed-4d2b6d803f24.png)
![image](https://user-images.githubusercontent.com/13535885/108517101-45cc3000-72c7-11eb-89c5-adc8aa2feeed.png)

I looked over my visualizer code and I'm nearly sure it's not the visualizer's code itself.

I just wanted to ask if these artefacts are suppost to be there or if they are an error in clover noise!

Thank you :)

**Comment by tommyettinger** [comment]
It looks like the hash function is very different in the GLSL code and the Java code, and the Java version's hash looks pretty bad just at a glance. You can see how the GLSL code looks in this ShaderToy, https://www.shadertoy.com/view/NllSzB ; it doesn't have the diagonal striping because its algorithm is significantly different (even if it's just the hashing, that's called many times). As for the Java code, there's a lot of beginner mistakes. It allocates constantly, at almost every step involved, which puts strain on Java's garbage collector that would be impossible not to see if using this on mobile devices. The `doHash()` method has an extraneous check for negative values, and it still can return negative values (such as when input is 0 and seed is `0x1000000000000L - 1L`, among lots of other combinations). It uses a relatively-expensive modulus operation with a power-of-two modulus, which could be replaced by `input &= 0xffffffffffffL;` if negative outputs aren't desirable, or better yet `input >>>= 16;`. Its only source of randomness now is from using the low 48 bits of a linear congruential generator, and only using one pass through it -- the most-random bits of an LCG are higher, rather than lower, and none are likely to be especially random with one pass.

A lot of this could be fixed! The algorithm here is pretty similar to jittered value noise, and if you like how it looks, there are much more efficient ways to compute that while still probably keeping much of the appearance similar. Value noise usually looks something like https://i.imgur.com/dHxU5jG.png with one octave (iteration, as Clover noise calls it) and with Hermite interpolation instead of the linear interpolation used here. Using multiple calls to value noise, rotating with each call and feeding the last value noise result into one component of the next call, then averaging and emphasizing extreme values gives https://i.imgur.com/pcg4XiK.png (that has one octave, though each involves multiple value noise calls). I implemented it here https://github.com/tommyettinger/make-some-noise/blob/master/other/make/some/noise/SimplexAndFoam.java#L1031-L1054 if you're interested.
